name: Login to Majsoul

on:
  schedule:
    - cron: '5 21 * * *'  # 21:05 UTC time (6:05 a.m. Korean time)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Execute month ticket automation
      run: npm start
      env:
        UID: ${{ secrets.UID }}
        TOKEN: ${{ secrets.TOKEN }}
        MS_HOST: ${{ secrets.MS_HOST }}

    - name: Update Keep-Alive File
      run: |
        echo "Last run: $(date)" > keep_alive.txt
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add keep_alive.txt
        git commit -m "Keep-alive: Update timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
